name: Generate GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: sanjithms
          show_icons: true
          include_all_commits: true
          count_private: true
          hide_border: true
          theme: dark
          output_path: assets/stats.svg

      - name: Generate language stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: sanjithms
          layout: compact
          langs_count: 8
          hide_border: true
          theme: dark
          output_path: assets/languages.svg

      - name: Commit and push SVGs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/*.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
