name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sanjithms
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: large
          filename: assets/stats.svg

      - name: Commit Metrics
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/stats.svg
          git commit -m "Update GitHub metrics" || echo "No changes"
          git push
