name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: sanjithms
          theme: dark
          hide_border: true
          show_icons: true
          output_path: assets/stats.svg

      - name: Generate Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: sanjithms
          theme: dark
          layout: compact
          hide_border: true
          output_path: assets/languages.svg

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/*.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
